---
# Source: check-port/templates/check-port.yaml
apiVersion: v1
kind: Service
metadata:
  name: check-port-server
  namespace: check
spec:
  type: ClusterIP
  selector:
    app: check-port-server
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
# Source: check-port/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: check-port-client
  namespace: check
  labels:
    k8s-app: check-port-client
    helm.sh/chart: check-port-0.1.0
    app.kubernetes.io/name: check-port
    app.kubernetes.io/instance: check-port
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      k8s-app: check-port-client
      app.kubernetes.io/name: check-port
      app.kubernetes.io/instance: check-port
  template:
    metadata:
      labels:
        k8s-app: check-port-client
        app.kubernetes.io/name: check-port
        app.kubernetes.io/instance: check-port
    spec:
      containers:
      - name: check-port-client
        image: steemax/net-check-client:v1.0.2
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
# Source: check-port/templates/deployment-serv.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-port-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-port
  template:
    metadata:
      labels:
        app: check-port
    spec:
      containers:
      - name: check-port-server
        image: steemax/net-check-server:v1.0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
---
# Source: check-port/templates/ingress.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: check-port-server
spec:
  entryPoints: websecure
  routes:
    - match: map[]
      kind: Rule
      services:
        - name: check-port-server
          kind: Service
          port: 8080
          scheme: https
