{{- if .Values.checkPortServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.checkPortServer.Deployment.name | default (printf "%s-server" (include "check-port.fullname" .)) }}
  namespace: check
spec:
  type: {{ .Values.checkPortServer.type }}
  selector:
    app: check-port-server
  ports:
	{{- .Values.checkPortServer.ports | toYaml | nindent 2 -}}
{{- end -}}